flags: {}
extra-package-dbs: []
packages:
- .
- location:
    git: https://github.com/tosku/prng.git
    extra-dep: true
    commit: 00697926a4cf8897e47de5e0e5cf3f6a8067f9b5
extra-deps:
- Histogram-0.1.0.2
- aeson-1.2.3.0
- binary-0.8.5.1
- containers-0.5.10.2
- criterion-1.2.3.0
- fgl-5.6.0.0
- natural-numbers-0.1.2.0
- statistics-0.14.0.2
resolver: lts-9.10
