flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- git: git@github.com:tosku/prng
  commit: 42bdc6a212e89238c649e144b322e7fa6ac9ca03
- Histogram-0.1.0.2
- aeson-1.2.3.0
- binary-0.8.5.1
- containers-0.5.10.2
- criterion-1.2.3.0
- fgl-5.6.0.0
- natural-numbers-0.1.2.0
- statistics-0.14.0.2
resolver: lts-10.3
