flags: {}
extra-package-dbs: []
packages:
- .
#- ../../graph/
resolver: lts-10.3
extra-deps:
- git: https://github.com/tosku/prng.git
  commit: 42bdc6a212e89238c649e144b322e7fa6ac9ca03
- git: https://github.com/tosku/graph.git
  commit: 0ba2a49f9c23a092d7f4bc815a21f46ba632e07c
- git: https://github.com/tosku/tesths.git
  commit: 0fb1ba49641e87b843556cd1441240ef602fcf2b
- Histogram-0.1.0.2
- Unique-0.4.7.2
- natural-numbers-0.1.2.0
allow-newer: true
